return {
	species = {
		-- by bitfield
		-- adress 0x063 Order 3
		-- parseddata['Monster Level Char field']
		--[0]='',
		[1]='Rabbit',
		[2]='Behemoth',
		[3]='Tiger',
		[4]='Sheep',
		[5]='Ram',
		[6]='Dhalmel',
		[7]='Coeurl',
		[8]='Opo-opo',
		[9]='Manticore',
		[10]='Buffalo',
		[11]='Marid',
		[12]='Cerberus',
		[13]='Gnole',
		--[14]='Yztarg', --not implemented
		[15]='Funguar',
		[16]='Treant Sapling',
		[17]='Morbol',
		[18]='Mandragora',
		[19]='Sabotender',
		[20]='Flytrap',
		[21]='Goobbue',
		[22]='Rafflesia',
		[23]='Panopt',
		--[24]='Belladonna', --not implemented
		--[25]='Leafkin', --not implemented
		--[26]='Snapweed', --not implemented
		[27]='Bee',
		[28]='Beetle',
		[29]='Crawler',
		[30]='Fly',
		[31]='Scorpion',
		[32]='Spider',
		[33]='Antlion',
		[34]='Diremite',
		[35]='Chigoe',
		[36]='Wamouracampa',
		[37]='Ladybug',
		[38]='Gnat',
		--[39]='Mantis', --not implemented
		--[40]='Kulox (Gnat)', --not implemented
		--[41]='Twitherym', --not implemented
		--[42]='Chapuli', --not implemented
		[43]='Lizard',
		[44]='Raptor',
		[45]='Adamantoise',
		[46]='Bugard',
		[47]='Eft',
		[48]='Wivre',
		[49]='Peiste',
		--[50]='Matamata', --not implemented
		--[51]='Worm', --not implemented
		[52]='Slime',
		[53]='Hecteyes',
		[54]='Flan',
		--[55]='Botulus (Flan)', --not implemented
		[56]='Slug',
		[57]='Sandworm',
		[58]='Leech',
		--[59]='Acuex', --not implemented
		[60]='Crab',
		[61]='Pugil',
		[62]='Sea Monk',
		[63]='Uragnite',
		[64]='Orobon',
		[65]='Ruszor',
		[66]='Toad',
		--[67]='Pteraketos', --not implemented
		--[68]='Craklaw', --not implemented
		[69]='Bird',
		[70]='Cockatrice',
		[71]='Roc',
		[72]='Bat',
		[73]='Hippogryph',
		[74]='Apkallu',
		[75]='Colibri',
		[76]='Amphiptere',
		--[77]='Harpeia', --not implemented
		--[78]='Tulfaire', --not implemented
		
		[254]='Astoltian Slime',
		[255]='Spriggan',
	},
	species_variants = {
		-- by bitfield +256
		-- adress 0x063 Order 4
		-- parseddata['Variants Bitfield']
		
		[256]='Onyx Rabbit',
		[257]='Alabaster Rabbit',
		[258]='Lapinion',

		[259]='Elasmoth',

		[261]='Legendary Tiger',
		[262]='Smilodon',

		[263]='Karakul',
		--[264]='Lucerewe (Sheep)',
		--[265]='Ovim (Sheep)',

		[266]='Lynx',
		[267]='Collared Lynx',

		[268]='Legendary Manticore',

		[269]='Orthrus',

		--[270]='Bipedal Gnole',

		[271]='Coppercap',

		[272]='Treant',
		--[273]='Flowering Treant',
		--[274]='Scarlet-tinged Treant',
		--[275]='Barren Treant',
		--[276]='Necklaced Treant',

		[277]='Pygmy Morbol',
		[278]='Scarce Morbol',
		[279]='Ameretat',
		[280]='Purbol',

		[281]='Korrigan',
		[282]='Lycopodium',
		[283]='Pygmy Mandragora',
		[284]='Adenium',
		[285]='Pachypodium',
		--[286]='Enlightened Mandragora',
		[287]='New Year Mandragora',

		[288]='Sabotender Florido',

		[289]='Mitrastema',

		[290]='Vermilion and Onyx Bee',
		[291]='Zaffre Bee',

		[292]='Onyx Beetle',
		[293]='Gamboge Beetle',

		[294]='Eruca',
		[295]='Emerald Crawler',
		[296]='Pygmy Emerald Crawler',

		[297]='Vermilion Fly',

		[298]='Scolopendrid',
		[299]='Unusual Scolopendrid',

		[300]='Reticulated Spider',
		[301]='Vermilion and Onyx Spider',

		[302]='Onyx Antlion',
		[303]='Formiceros',

		[304]='Arundimite',

		[305]='Azure Chigoe',

		--[306]='Coiled Wamouracampa',
		[307]='Wamoura',
		[308]='Coral Wamoura',

		[309]='Gold Ladybug',

		[310]='Midge',

		--[311]='Vermilion Mantis',
		--[312]='Russet Mantis',

		[315]='Ashen Lizard',

		[316]='Emerald Raptor',
		[317]='Vermilion Raptor',

		[318]='Pygmy Adamantoise',
		[319]='Legendary Adamantoise',
		[320]='Ferromantoise',

		[321]='Abyssobugard',

		[322]='Tarichuk',

		[323]='Unusual Wivre',

		[324]='Sibilus',

		--[326]='Vermilion Worm',
		--[327]='Onyx Worm',
		--[328]='Entozoon (Worm)',

		[329]='Clot',
		[330]='Gold Slime',
		[331]='Boil',

		[332]='Gold Flan',
		[333]='Blancmange',

		[334]='Pygmy Sandworm',
		[335]='Gigaworm',

		[336]='Azure Leech',
		[337]='Obdella',

		[340]='Vermilion Crab',
		[341]='Hermitage Crab',
		[342]='Vermilion Hermitage Crab',
		[343]='Porter Crab',

		[344]='Jagil',
		[345]='Azure Sea Monk',

		[346]='Limascabra',

		[347]='Pygmy Orobon',
		[348]='Ogrebon',

		[349]='Azure Toad',
		[350]='Vermilion Toad',

		[351]='Onyx Bird',

		[352]='Ziz',

		[353]='Legendary Roc',
		[354]='Gagana',

		[355]='Bats',
		[356]='Vermilion Bat',
		[357]='Vermilion Bats',

		[358]='Inguza',

		[359]='Toucalibri',

		[360]='Sanguiptere',

		--[361]='Vermilion Harpeia',
		--[362]='Alabaster Harpeia',
		
		[508]='She-Slime',
		[509]='Metal Slime',
		[510]='Spriggan.C',
		[511]='Spriggan.G',
	},
	racejobinstincts = {
		-- by bitfield
		-- adress 0x063 Order 4
		-- parseddata['Instinct Bitfield 3']
		[0]='Hume instinct',
		[1]='Elvaan instinct',
		[2]='Tarutaru instinct',
		[3]='Mithra instinct',
		[4]='Galka instinct',
		
		[5]='Hume instinct II',
		[6]='Elvaan instinct II',
		[7]='Tarutaru instinct II',
		[8]='Mithra instinct II',
		[9]='Galka instinct II',
		
		[10]='WAR instinct',
		[11]='MNK instinct',
		[12]='WHM instinct',
		[13]='BLM instinct',
		[14]='RDM instinct',
		[15]='THF instinct',
		[16]='PLD instinct',
		[17]='DRK instinct',
		[18]='BST instinct',
		[19]='BRD instinct',
		[20]='RNG instinct',
		[21]='SAM instinct',
		[22]='NIN instinct',
		[23]='DRG instinct',
		[24]='SMN instinct',
		[25]='BLU instinct',
		[26]='COR instinct',
		[27]='PUP instinct',
		[28]='DNC instinct',
		[29]='SCH instinct',
		[30]='GEO instinct',
		[31]='RUN instinct',
	},
	monsterinstincts = {
		--[1] = ". Ins. I",
		--[2] = ". Ins. II",
		--[3] = ". Ins. III",
		[4] = "Rabbit Ins. I",
		[5] = "Rabbit Ins. II",
		[6] = "Rabbit Ins. III",
		[7] = "Behemoth Ins. I",
		[8] = "Behemoth Ins. II",
		[9] = "Behemoth Ins. III",
		[10] = "Tiger Ins. I",
		[11] = "Tiger Ins. II",
		[12] = "Tiger Ins. III",
		[13] = "Sheep Ins. I",
		[14] = "Sheep Ins. II",
		[15] = "Sheep Ins. III",
		[16] = "Ram Ins. I",
		[17] = "Ram Ins. II",
		[18] = "Ram Ins. III",
		[19] = "Dhalmel Ins. I",
		[20] = "Dhalmel Ins. II",
		[21] = "Dhalmel Ins. III",
		[22] = "Coeurl Ins. I",
		[23] = "Coeurl Ins. II",
		[24] = "Coeurl Ins. III",
		[25] = "Opo-opo Ins. I",
		[26] = "Opo-opo Ins. II",
		[27] = "Opo-opo Ins. III",
		[28] = "Manticore Ins. I",
		[29] = "Manticore Ins. II",
		[30] = "Manticore Ins. III",
		[31] = "Buffalo Ins. I",
		[32] = "Buffalo Ins. II",
		[33] = "Buffalo Ins. III",
		[34] = "Marid Ins. I",
		[35] = "Marid Ins. II",
		[36] = "Marid Ins. III",
		[37] = "Cerberus Ins. I",
		[38] = "Cerberus Ins. II",
		[39] = "Cerberus Ins. III",
		[40] = "Gnole Ins. I",
		[41] = "Gnole Ins. II",
		[42] = "Gnole Ins. III",
		--[43] = "Yztarg Ins. I",
		--[44] = "Yztarg Ins. II",
		--[45] = "Yztarg Ins. III",
		[46] = "Funguar Ins. I",
		[47] = "Funguar Ins. II",
		[48] = "Funguar Ins. III",
		[49] = "Treant Ins. I",
		[50] = "Treant Ins. II",
		[51] = "Treant Ins. III",
		[52] = "Morbol Ins. I",
		[53] = "Morbol Ins. II",
		[54] = "Morbol Ins. III",
		[55] = "Mandragora Ins. I",
		[56] = "Mandragora Ins. II",
		[57] = "Mandragora Ins. III",
		[58] = "Sabotender Ins. I",
		[59] = "Sabotender Ins. II",
		[60] = "Sabotender Ins. III",
		[61] = "Flytrap Ins. I",
		[62] = "Flytrap Ins. II",
		[63] = "Flytrap Ins. III",
		[64] = "Goobbue Ins. I",
		[65] = "Goobbue Ins. II",
		[66] = "Goobbue Ins. III",
		[67] = "Rafflesia Ins. I",
		[68] = "Rafflesia Ins. II",
		[69] = "Rafflesia Ins. III",
		[70] = "Panopt Ins. I",
		[71] = "Panopt Ins. II",
		[72] = "Panopt Ins. III",
		--[73] = "Belladonna Ins. I",
		--[74] = "Belladonna Ins. II",
		--[75] = "Belladonna Ins. III",
		--[76] = "Leafkin Ins. I",
		--[77] = "Leafkin Ins. II",
		--[78] = "Leafkin Ins. III",
		--[79] = "Snapweed Ins. I",
		--[80] = "Snapweed Ins. II",
		--[81] = "Snapweed Ins. III",
		[82] = "Bee Ins. I",
		[83] = "Bee Ins. II",
		[84] = "Bee Ins. III",
		[85] = "Beetle Ins. I",
		[86] = "Beetle Ins. II",
		[87] = "Beetle Ins. III",
		[88] = "Crawler Ins. I",
		[89] = "Crawler Ins. II",
		[90] = "Crawler Ins. III",
		[91] = "Fly Ins. I",
		[92] = "Fly Ins. II",
		[93] = "Fly Ins. III",
		[94] = "Scorpion Ins. I",
		[95] = "Scorpion Ins. II",
		[96] = "Scorpion Ins. III",
		[97] = "Spider Ins. I",
		[98] = "Spider Ins. II",
		[99] = "Spider Ins. III",
		[100] = "Antlion Ins. I",
		[101] = "Antlion Ins. II",
		[102] = "Antlion Ins. III",
		[103] = "Diremite Ins. I",
		[104] = "Diremite Ins. II",
		[105] = "Diremite Ins. III",
		[106] = "Chigoe Ins. I",
		[107] = "Chigoe Ins. II",
		[108] = "Chigoe Ins. III",
		[109] = "Wamoura Ins. I",
		[110] = "Wamoura Ins. II",
		[111] = "Wamoura Ins. III",
		[112] = "Ladybug Ins. I",
		[113] = "Ladybug Ins. II",
		[114] = "Ladybug Ins. III",
		[115] = "Gnat Ins. I",
		[116] = "Gnat Ins. II",
		[117] = "Gnat Ins. III",
		--[118] = "Mantis Ins. I",
		--[119] = "Mantis Ins. II",
		--[120] = "Mantis Ins. III",
		--[121] = "Kulox (Gnat) Ins. I",
		--[122] = "Kulox (Gnat) Ins. II",
		--[123] = "Kulox (Gnat) Ins. III",
		--[124] = "Twitherym Ins. I",
		--[125] = "Twitherym Ins. II",
		--[126] = "Twitherym Ins. III",
		--[127] = "Chapuli Ins. I",
		--[128] = "Chapuli Ins. II",
		--[129] = "Chapuli Ins. III",
		[130] = "Lizard Ins. I",
		[131] = "Lizard Ins. II",
		[132] = "Lizard Ins. III",
		[133] = "Raptor Ins. I",
		[134] = "Raptor Ins. II",
		[135] = "Raptor Ins. III",
		[136] = "Adamantoise Ins. I",
		[137] = "Adamantoise Ins. II",
		[138] = "Adamantoise Ins. III",
		[139] = "Bugard Ins. I",
		[140] = "Bugard Ins. II",
		[141] = "Bugard Ins. III",
		[142] = "Eft Ins. I",
		[143] = "Eft Ins. II",
		[144] = "Eft Ins. III",
		[145] = "Wivre Ins. I",
		[146] = "Wivre Ins. II",
		[147] = "Wivre Ins. III",
		[148] = "Peiste Ins. I",
		[149] = "Peiste Ins. II",
		[150] = "Peiste Ins. III",
		--[151] = "Matamata Ins. I",
		--[152] = "Matamata Ins. II",
		--[153] = "Matamata Ins. III",
		--[154] = "Worm Ins. I",
		--[155] = "Worm Ins. II",
		--[156] = "Worm Ins. III",
		[157] = "Slime Ins. I",
		[158] = "Slime Ins. II",
		[159] = "Slime Ins. III",
		[160] = "Hecteyes Ins. I",
		[161] = "Hecteyes Ins. II",
		[162] = "Hecteyes Ins. III",
		[163] = "Flan Ins. I",
		[164] = "Flan Ins. II",
		[165] = "Flan Ins. III",
		--[166] = "Botulus (Flan) Ins. I",
		--[167] = "Botulus (Flan) Ins. II",
		--[168] = "Botulus (Flan) Ins. III",
		[169] = "Slug Ins. I",
		[170] = "Slug Ins. II",
		[171] = "Slug Ins. III",
		[172] = "Sandworm Ins. I",
		[173] = "Sandworm Ins. II",
		[174] = "Sandworm Ins. III",
		[175] = "Leech Ins. I",
		[176] = "Leech Ins. II",
		[177] = "Leech Ins. III",
		--[178] = "Acuex Ins. I",
		--[179] = "Acuex Ins. II",
		--[180] = "Acuex Ins. III",
		[181] = "Crab Ins. I",
		[182] = "Crab Ins. II",
		[183] = "Crab Ins. III",
		[184] = "Pugil Ins. I",
		[185] = "Pugil Ins. II",
		[186] = "Pugil Ins. III",
		[187] = "Sea Monk Ins. I",
		[188] = "Sea Monk Ins. II",
		[189] = "Sea Monk Ins. III",
		[190] = "Uragnite Ins. I",
		[191] = "Uragnite Ins. II",
		[192] = "Uragnite Ins. III",
		[193] = "Orobon Ins. I",
		[194] = "Orobon Ins. II",
		[195] = "Orobon Ins. III",
		[196] = "Ruszor Ins. I",
		[197] = "Ruszor Ins. II",
		[198] = "Ruszor Ins. III",
		[199] = "Toad Ins. I",
		[200] = "Toad Ins. II",
		[201] = "Toad Ins. III",
		--[202] = "Pteraketos Ins. I",
		--[203] = "Pteraketos Ins. II",
		--[204] = "Pteraketos Ins. III",
		--[205] = "Craklaw Ins. I",
		--[206] = "Craklaw Ins. II",
		--[207] = "Craklaw Ins. III",
		[208] = "Bird Ins. I",
		[209] = "Bird Ins. II",
		[210] = "Bird Ins. III",
		[211] = "Cockatrice Ins. I",
		[212] = "Cockatrice Ins. II",
		[213] = "Cockatrice Ins. III",
		[214] = "Roc Ins. I",
		[215] = "Roc Ins. II",
		[216] = "Roc Ins. III",
		[217] = "Bat Ins. I",
		[218] = "Bat Ins. II",
		[219] = "Bat Ins. III",
		[220] = "Hippogryph Ins. I",
		[221] = "Hippogryph Ins. II",
		[222] = "Hippogryph Ins. III",
		[223] = "Apkallu Ins. I",
		[224] = "Apkallu Ins. II",
		[225] = "Apkallu Ins. III",
		[226] = "Colibri Ins. I",
		[227] = "Colibri Ins. II",
		[228] = "Colibri Ins. III",
		[229] = "Amphiptere Ins. I",
		[230] = "Amphiptere Ins. II",
		[231] = "Amphiptere Ins. III",
		--[232] = "Harpeia Ins. I",
		--[233] = "Harpeia Ins. II",
		--[234] = "Harpeia Ins. III",
		--[235] = "Tulfaire Ins. I",
		--[236] = "Tulfaire Ins. II",
		--[237] = "Tulfaire Ins. III",
		[763] = "A. Slime Ins. I",
		[764] = "A. Slime Ins. II",
		[765] = "A. Slime Ins. III",
		[766] = "E. Spriggan Ins. I",
		[767] = "E. Spriggan Ins. II",
		[768] = "E. Spriggan Ins. III",
	}
}